# ~/.aerospace.toml  (CLEAN)

after-startup-command = []
start-at-login = true

# Normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Layouts
default-root-container-layout = 'tiles'            # 'tiles' | 'accordion'
default-root-container-orientation = 'horizontal'  # 'horizontal' | 'vertical' | 'auto'
accordion-padding = 36

# TOP-LEVEL ONLY (not inside any block):
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

# -------------------------
# Gaps (per-monitor override) — single assignment per key
# -------------------------
[gaps]
inner.horizontal = [
  { monitor."CR320QB" = 16 },
  { monitor."Color LCD" = 8 },
  8
]

inner.vertical = [
  { monitor."CR320QB" = 16 },
  { monitor."Color LCD" = 8 },
  8
]

outer.left = [
  { monitor."CR320QB" = 24 },
  { monitor."Color LCD" = 12 },
  12
]

outer.right = [
  { monitor."CR320QB" = 24 },
  { monitor."Color LCD" = 12 },
  12
]

outer.top = [
  { monitor."CR320QB" = 120 },
  { monitor."Color LCD" = 12 },
  12
]

outer.bottom = [
  { monitor."CR320QB" = 30 },
  { monitor."Color LCD" = 12 },
  12
]
# -------------------------
# Valid on-window-detected entries (ONLY these keys inside)
# -------------------------
# [[on-window-detected]]
# if.app-id = "com.google.Chrome"
# run = "move-node-to-workspace current"
#
# [[on-window-detected]]
# if.app-id = "com.apple.Safari"
# run = "move-node-to-workspace current"
#
# [[on-window-detected]]
# if.app-id = "com.googlecode.iterm2"
# run = "move-node-to-workspace current"

# -------------------------
# Keybindings (main mode)
# -------------------------
[mode.main.binding]
# Layout toggles
alt-slash  = 'layout tiles horizontal vertical'
alt-comma  = 'layout accordion horizontal vertical'
alt-f      = 'layout floating tiling'
alt-backslash = 'balance-sizes'

# Focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move windows
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize (bigger steps for 32")
alt-minus = 'resize smart -100'
alt-equal = 'resize smart +100'

# “Make right pane wide” macro (no service mode needed)
alt-w = 'resize smart +300'

alt-shift-r = 'flatten-workspace-tree'

# Convenience mouse helper
alt-m = 'move-mouse window-lazy-center'

# Workspaces 1–9
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# Move node to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# Quick workspace ops
alt-tab       = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-semicolon = 'mode service'
alt-shift-t = ['flatten-workspace-tree', 'layout tiles horizontal']
alt-shift-s = [
  "flatten-workspace-tree",
  "layout tiles horizontal",
  "focus right",
  "join-with down"
]

# -------------------------
# Service mode
# -------------------------
[mode.service.binding]
esc = ['reload-config', 'mode main']
r   = ['flatten-workspace-tree', 'mode main']
f   = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

# Join
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# Media
down       = 'volume down'
up         = 'volume up'
shift-down = ['volume set 0', 'mode main']

# -------------------------
# Pin key workspaces to CR320QB
# -------------------------
[workspace-to-monitor-force-assignment]
"1" = "CR320QB"
"2" = "CR320QB"
"3" = "CR320QB"

# [[on-app-activated]]
# run = "move-node-to-workspace current"
