apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    finalizers:
    - kubernetes.io/pvc-protection
    name: odysseus-sailing-data-pvc
    namespace: odysseus-sailing-data-dev
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
    storageClassName: ""
    volumeMode: Filesystem
    volumeName: odysseus-sailing-data-smb
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 50Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
