#!/usr/bin/env bash
app_name=$1
set -e
set pipefail
app_home=$HOME/src/gitrepo/costco/ado/k8s-iac/argocd/apps/$app_name
if ! [[ -e $app_home ]]
then
   echo $app_home not exist
   exit -1
fi

pushd $app_home
swagger_ui=swagger-ui\/index.html
prefix=$(rg -C 1 httpGet values.yaml | perl -nle 'print $1 if /path: \/(api\/mesh|api\/egress)/' | uniq)
if [[ ! -z "${prefix}" ]]; then
   export swagger=$prefix\/$swagger_ui
else
   export swagger=$swagger_ui
fi
rg -C 2 ingressGateway | perl -nle 'print "https://$1/$ENV{'swagger'}" if /host: (.*)/' | rg -v fully | rg -v some | rg -v prod > /tmp/services.txt

vi -c "%s#\zehttps://${app_name}\(-\(\w\+\)\|.*.\(dev\)\)#\2\3 - " -c noh -c sort -c 'w!' -c 'norm G | ma | o ' -c 'wq!' /tmp/services.txt
vi -c "1,'at$ | 'a+2" -c 'sil! .,$s/\w\+ -/curl -s -w "%{response_code}"/' -c 'w!' -c 'noh | norm gg' /tmp/services.txt
popd
