#!/usr/bin/env bash
tkgi get-credentials --sso-auto us03l81k8sc22
tkgi get-credentials --sso-auto us03l81k8sc32
tkgi get-credentials --sso-auto us03l81k8sc42
tkgi get-credentials --sso-auto us03l81k8sc71

cp -v /mnt/c/Users/chengkai.liang/.kube/config ~/.kube/config
